Update json-validation.yml

diff --git a/.github/workflows/json-validation.yml b/.github/workflows/json-validation.yml
--- a/.github/workflows/json-validation.yml
+++ b/.github/workflows/json-validation.yml
@@ -20,27 +20,33 @@ jobs:
       - name: Install jq
         run: sudo apt-get install jq
 
-      - name: Validate data.json
+      - name: Validate JSON
         run: |
-          if ! jq -e '
-            # Check if the file contains valid JSON
-            try (. | fromjson | . != null) catch false as $valid_json |
-            
-            # Check for the "description" property (optional)
-            .description? as $desc |
-            
-            # Check for the "socials" property (optional)
-            .socials? as $socials |
-            
-            # Check if the "socials" property is an object with valid URLs
-            ($socials == null or
-              ($socials | objects | all(. as $value | ($value | strings | test("^https?://"))))) and
-            
-            # Check that there are no additional properties
-            (keys - ["description", "socials"] | length == 0)
-          ' data.json; then
-            echo "JSON validation failed."
-            exit 1
-          else
-            echo "JSON validation passed."
-          fi
+          # Find all JSON files in the pull request
+          json_files=$(git diff --name-only HEAD^..HEAD | grep '\.json$')
+
+          # Loop through JSON files and validate each one
+          for file in $json_files; do
+            if ! jq -e '
+              # Check if the file contains valid JSON
+              try (. | fromjson | . != null) catch false as $valid_json |
+              
+              # Check for the "description" property (optional)
+              .description? as $desc |
+              
+              # Check for the "socials" property (optional)
+              .socials? as $socials |
+              
+              # Check if the "socials" property is an object with valid URLs
+              ($socials == null or
+                ($socials | objects | all(. as $value | ($value | strings | test("^https?://"))))) and
+              
+              # Check that there are no additional properties
+              (keys - ["description", "socials"] | length == 0)
+            ' "$file"; then
+              echo "JSON validation failed for $file."
+              exit 1
+            else
+              echo "JSON validation passed for $file."
+            fi
+          done
