Update json-validation.yml

diff --git a/.github/workflows/json-validation.yml b/.github/workflows/json-validation.yml
--- a/.github/workflows/json-validation.yml
+++ b/.github/workflows/json-validation.yml
@@ -30,11 +30,13 @@ jobs:
           # Get the list of changed JSON files from the environment file
           json_files=$(echo "$steps.files.outputs.all" | grep '\.json$')
 
+          echo "Files: $json_files"
+          
           failed_files=""
 
           # Loop through JSON files and validate each one
           for file in $json_files; do
-            if !(jq -e '
+            if ! (jq -e '
               # Check if the file contains valid JSON
               try (. | fromjson | . != null) catch false as $valid_json |
               
@@ -57,6 +59,8 @@ jobs:
 
           # Output the list of failed files
           echo "::set-output name=failed_files::$failed_files"
+
+          echo "Failed checks: $failed_files"
           
   check_issues:
     needs: validate
