Update json-validation.yml

diff --git a/.github/workflows/json-validation.yml b/.github/workflows/json-validation.yml
--- a/.github/workflows/json-validation.yml
+++ b/.github/workflows/json-validation.yml
@@ -29,7 +29,7 @@ jobs:
           
           # Loop through JSON files and validate each one
           for file in $json_files; do
-            echo "Checking $file"
+            echo "Checking $file" >&1
             if ! jq -e '
               # Check if the file contains valid JSON
               try (. | fromjson | . != null) catch false as $valid_json |
@@ -47,9 +47,9 @@ jobs:
               # Check that there are no additional properties
               (keys - ["description", "socials"] | length == 0)
             ' "$file"; then
-              echo "JSON validation failed for $file."
+              echo "JSON validation failed for $file." >&2
               exit 1
             else
-              echo "JSON validation passed for $file."
+              echo "JSON validation passed for $file." >&1
             fi
           done
